#+STARTUP: showall
#+TITLE:     My Emacs Configuration
#+AUTHOR:    Jonathan Chu
#+EMAIL:     me@jonathanchu.is
#+DATE:      2015-03-01

** TODO TODO
- [X] Introduction
- [X] Installation
- [ ] Requirements
- [ ] Updates
- [X] Global config
- [ ] Functions
- [ ] Modes
- [ ] Key bindings

** Introduction

This is my emacs configuration, a somewhat simple config compared to
most. It's geared towards OS X, although it should work on most *nix
configs. I've never tried this on Windows, so YMMV.

The entire configuration is one file =~/.emacs.d/init.el= and aims to
provide you with a barebones configuration with sane defaults, built
upon =package.el=.

Although emacs has support for many programming languages, this
config is geared towards the following languages and workflows:

- Python
- CSS / LESS
- JavaScript
- Markdown
- Clojure


** Installation

To install, it's recommended to clone this repo wherever you prefer
and symlink the directory to =~/.emacs.d=.

: git clone https://github.com/jonathanchu/dotemacs.git

There is a =Makefile= provided that will create the symlink for you at
=~/.emacs.d=:

: make setup

My emacs distro of choice is:

: brew install emacs --with-cocoa

Please note, this requires [[http://brew.sh][homebrew]] to be installed.


** Requirements

There are a few requirements needed for this config to properly run.
All of these prerequisites can be installed via `homebrew` and `npm`.

- brew install ag
- brew install node
- npm install jshint


** Updates

To update the packages, type @@html:<kbd>@@M-x
list-packages@@html:</kbd>@@, then @@html:<kbd>@@U@@html:</kbd>@@
followed by @@html:<kbd>@@x@@html:</kbd>@@.

** Global Config

There are some very common things that most Emacs users do to setup
and configure their text editor environment.

: (fset 'yes-or-no-p 'y-or-n-p)  ;; only type 'y' or 'n' instead of 'yes' or 'no'
: (setq inhibit-splash-screen t)  ;; no splash screen
: (setq initial-scratch-message nil)  ;; no message on startup
: (menu-bar-mode -1)  ;; no menu bar
: (setq fill-column 80)  ;; M-q
: (when (functionp 'tool-bar-mode)
:   (tool-bar-mode -1))  ;; no toolbar
: (if window-system
:     (progn
:       (scroll-bar-mode -1)  ;; disable scroll bars
:       (set-frame-font "Inconsolata 15"))) ;; set font
: (set-face-attribute 'default nil :height 160)  ;; make the font more visually pleasing
: (setq mac-allow-anti-aliasing t)  ;; nice fonts in OS X
: (setq-default truncate-lines 1)  ;; no word wrap
: (setq-default line-spacing 4)
: (setq-default indent-tabs-mode nil)  ;; no tabs


** Functions


** Modes


** Key bindings

I prefer to use `smex` instead of the default
@@html:<kbd>@@M-x@@html:</kbd>@@ behavior. I map `smex` to
@@html:<kbd>@@M-x@@html:</kbd>@@.
