#+STARTUP: showall
#+TITLE:     My Emacs Configuration
#+AUTHOR:    Jonathan Chu
#+EMAIL:     me@jonathanchu.is
#+DATE:      2016-01-02

** Introduction

   This is my Emacs configuration, a somewhat simple config compared
   to most. It's geared towards OS X, although it should work on most
   *nix configs. I've never tried this on Windows, so YMMV.

   The entire configuration is tangled using =org-babel-load-file=,
   which generates a file named =emacs-init.org= from the =emacs-lisp=
   source blocks. You can find the init org file here - [[https://github.com/jonathanchu/dotemacs/blob/master/emacs-init.org][my literate
   Emacs]].

   This configuration aims to provide you with a bare-bones
   configuration with sane defaults, built upon =package.el=.

   Although emacs has support for many programming languages, this
   config is geared towards the following languages and workflows:

- Python
- CSS / LESS
- JavaScript
- Markdown
- Clojure


** Installation

   To install, it's recommended to clone this repo wherever you prefer
   and symlink the directory to =~/.emacs.d=.

   #+BEGIN_SRC
   git clone https://github.com/jonathanchu/dotemacs.git
   #+END_SRC

   There is a =Makefile= provided that will create the symlink for you at
   =~/.emacs.d=:

   #+BEGIN_SRC
   make setup
   #+END_SRC

   My current emacs distro of choice is:

   #+BEGIN_SRC
   brew install emacs --with-cocoa
   #+END_SRC

   Please note, this requires [[http://brew.sh][homebrew]] to be installed.

** Requirements

   There are a few requirements needed for this config to properly run.
   All of these prerequisites can be installed via =homebrew= and =npm=.

   #+BEGIN_SRC
   brew install ag
   brew install node
   npm install jshint
   #+END_SRC

   For using =python-mode= and =elpy=, you'll need to have =pip=
   installed and install the following packages:

   #+BEGIN_SRC
   pip install rope
   pip install flake8
   #+END_SRC

** Updates

   To update the packages, type @@html:<kbd>@@M-x
   list-packages@@html:</kbd>@@, then @@html:<kbd>@@U@@html:</kbd>@@
   followed by @@html:<kbd>@@x@@html:</kbd>@@.

   I recently started to use @Malabarba's excellent [[https://github.com/Malabarba/paradox/][paradox]], which can be
   invoked similarly as such - @@html:<kbd>@@M-x
   paradox-list-packages@@html:</kbd>@@, then
   @@html:<kbd>@@U@@html:</kbd>@@ followed by
   @@html:<kbd>@@x@@html:</kbd>@@.
